=== RickyCT13/LMSGI/Act4Clientes/gestoria.dtd
<!ELEMENT gestoria (alta)*>
    <!ELEMENT alta (sede, cliente)>
        <!ELEMENT sede (empleado, fecha)>
            <!ELEMENT empleado (#PCDATA)>
            <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT cliente (descripcion, num_viviendas, vivienda+)>
            <!ELEMENT descripcion (Solvente|Insolvente)?>
            <!ELEMENT num_viviendas (#PCDATA)>
            <!ELEMENT vivienda (coste, resumen, plazo)>
                <!ELEMENT coste (#PCDATA)>
                <!ELEMENT resumen (#PCDATA)>
                <!ELEMENT plazo (#PCDATA)>

<!ATTLIST sede id_sede ID #REQUIRED>
<!ATTLIST cliente id_cliente ID #REQUIRED>
<!ATTLIST vivienda id_vivienda CDATA #REQUIRED>

=== RickyCT13/LMSGI/Act4Clientes/gestoria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE gestoria SYSTEM "gestoria.dtd">-->
<?xml-model href="gestoria.xsd"?>
<gestoria>
    <alta>
        <sede id_sede="A23584912">
            <empleado>Fulanito Gómez</empleado>
            <fecha>2020-01-02</fecha>
        </sede>
        <cliente id_cliente="ABC-123">
            <descripcion>Solvente</descripcion>
            <num_viviendas>2</num_viviendas>
            <vivienda ID="001">
                <coste_vivienda>23000</coste_vivienda>
                <resumen>Piso con buena ubicación, espacio promedio y en buenas condiciones.</resumen>
                <plazo>15</plazo>
            </vivienda>
            <vivienda ID="002">
                <coste_vivienda>30000</coste_vivienda>
                <resumen>Casa en un pueblo cercano, espaciosa aunque con arquitectura algo anticuada.</resumen>
                <plazo>23</plazo>
            </vivienda>
        </cliente>
    </alta>
</gestoria>
